config/routes.rb
# Load Resque Server
require 'resque/scheduler'
require 'resque/scheduler/server'
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # namespace :api do
  #   namespace :v1 do
  #     resources :urls do
  #       collection do
  #         get 'top_100'
  #         get 'decode_url'
  #       end
  #     end
  #   end
  # end
  #Define Url Routes using api/v1 namespace

  mount Sidekiq::Web => 'api/sidekiq'
  get 'api/v1/top' , to: "api/v1/urls#top_100"
  get '/' , to: "api/v1/urls#index"
  post '/url' , to: "api/v1/urls#create"
  get '/:word', to: "api/v1/urls#decode_url"

  # mount Resque::Server.new, at: "/resque"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
# == Schema Information
#
# Table name: urls
#
#  id             :bigint           not null, primary key
#  title          :string(500)
#  url            :text
#  short_url      :string(350)
#  times_accessed :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Url < ApplicationRecord
  include BaseEncoders
  # Validations for url attribute not null, unique and valid url
  validates :url, presence: true
  validates_uniqueness_of :url
  validates :url, url: { no_local: true, schemas: %w(https http)}

  after_save :encode_url

  def self.fetch_web_page_title(id)
    begin
      url_change = self.find(id)
      puts url_change.url
      title_tag = Nokogiri::HTML::Document.parse(HTTParty.get(url_change.url).body).title
      url_change.title = title_tag
      url_change.save
    rescue
        Rails.logger.error p 'Error fetching url '
    end
  end
  # Get top urls ordered by most times_accessed
  def self.get_top(top_limit)
      self.order('times_accessed DESC').limit(top_limit)
  end

  def self.get_entire_url_decoded(short_url)
      # Get entire url using the short_url stored
      short_url = BaseEncoders::Base62.new.extract_valid_base_characters(short_url)
      id = BaseEncoders::Base62.new.decode_from_base(short_url, 62)
      url_founded = self.find_by id: id
      if !url_founded.nil?
        url_founded.increment!(:times_accessed)
      end
      url_founded
  end

  private

  def encode_url
    # Encode id using a base62 encoder valid values [0-9a-zA-Z]
    # Initialize times accessed to 0
    self.update_columns(
        short_url: BaseEncoders::Base62.new.encode_to_base(self.id, 62),
        times_accessed: 0
    )
    true
  end
end

app/controllers/api/v1/urls_controller.rb
class Api::V1::UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]
  protect_from_forgery
  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.get_top(25)
    # render json: @urls
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    render json: @url
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  def top_100
    @urls = Url.get_top(top_limit=100)
    render json: @urls
  end

  def decode_url
    url_decoded = Url.get_entire_url_decoded(params[:word])
    print(url_decoded)
    if url_decoded.nil?
      render :file => 'public/404.html', :status => :not_found, :layout => false
    else
      redirect_to url_decoded.url
    end
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)
    respond_to do |format|
      if @url.save
            #format.html { redirect_to @url, notice: 'Url was successfully created.' }
        FetchUrlWorker.perform_async(@url.id)
        format.json { render json: {
                short_url: "#{request.protocol}#{request.host_with_port}/#{@url.short_url}",
                status: :created,
                location: @url }
            }
      else
        # format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.permit(:url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShorterner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url, local: true) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="field">
    <%= form.label :short_url %>
    <%= form.text_field :short_url %>
  </div>

  <div class="field">
    <%= form.label :times_accessed %>
    <%= form.number_field :times_accessed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Short url</th>
      <th>Times accessed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.title %></td>
        <td><%= url.url %></td>
        <td><%= url.short_url %></td>
        <td><%= url.times_accessed %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @url.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @url.url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @url.short_url %>
</p>

<p>
  <strong>Times accessed:</strong>
  <%= @url.times_accessed %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>